--1.2 David Dick
-- CS 342
--- Lab 1
--A 
SELECT * FROM DEPARTMENTS;

--B
SELECT COUNT(*) FROM EMPLOYEES;

--C I
select first_name, last_name from employees where salary > 15000;

-- C II
select first_name, last_name from employees where HIRE_DATE BETWEEN TO_DATE ('01/01/2002', 'mm/dd/yyyy') AND TO_DATE('01/01/2005','mm/dd/yyyy');
-- C III
SELECT * FROM EMPLOYEES WHERE PHONE_NUMBER NOT LIKE '515%';

-- D
SELECT FIRST_NAME || ' '|| LAST_NAME FROM DEPARTMENTS, EMPLOYEES WHERE DEPARTMENTS.DEPARTMENT_NAME = 'Finance' AND EMPLOYEES.DEPARTMENT_ID =  DEPARTMENTS.DEPARTMENT_ID ORDER BY EMPLOYEES.LAST_NAME;


-- E
SELECT CITY, STATE_PROVINCE, COUNTRY_NAME FROM LOCATIONS, REGIONS, COUNTRIES WHERE COUNTRIES.COUNTRY_ID = LOCATIONS.COUNTRY_ID AND COUNTRIES.REGION_ID = REGIONS.REGION_ID AND REGIONS.REGION_NAME = 'Asia';

--- F
SELECT * FROM LOCATIONS WHERE STATE_PROVINCE IS NULL;


